feat: Add mobile menu
moshoodabdullahi/portfolio pull request #7
Opened 2023-10-09 22:39 UTC by moshoodabdullahi

# This PR adds the seventh milestone to the portfolio website making use of classList to implement the mobile menu following the layout in [Figma Design](https://www.figma.com/file/LKueaSlr8Kc2yMKeZkKgtm/portfolio_project?type=design&node-id=0-1&t=3pMvwe6OjbChOBN7-0) link of the project and also the [Link](https://github.com/bolah2009/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md) of the mobile menu assignment

2023-10-10 08:53 UTC, Yinkusadel requested changes
plz do give the hamburger icon, the close icon and the links a hover effect aside that youre good to go 😊😊

2023-10-13 20:43 UTC, Yinkusadel commented
![image](https://github.com/moshoodabdullahi/portfolio/assets/105943931/fc2ae0f6-381e-4b8d-b461-8fdfbc0afae8)
looks fine tho i noticed i can spam your mobile menu till desktop version plz fix that and its all good

2023-10-20 07:55 UTC, Yinkusadel commented
![image](https://github.com/moshoodabdullahi/portfolio/assets/105943931/9a7543a8-1c7e-4755-8ce6-08f4589c91b0)
u seem to have issue with ur links effect here

2023-10-24 05:49 UTC, teckcipher requested changes
Let's address the comments below.

2023-10-24 05:49 UTC, teckcipher commented on Icon - Cancel.svg
Let's make the file names lower case with not space

2023-10-24 05:49 UTC, teckcipher commented on Icon - Menu.svg
If these icons are not use, we can delete it

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +    font-family: poppins, sans-serif;
Let's move all font family to CSS variables

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +    font: 700 18px poppins, sans-serif;
Same here

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +}
Let's remove all form of compound selector, using simple selectors make it easier to overwrite styles.

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +  cursor: pointer;
Why is this element a pointer only when it is hovered? If it's an element that should be pointer then it should with or without hover. I would recommend moving this into general styles. Alternatively, make the element a button and have a general style at the top to make all button elements a pointer cursor and remove all default styles such as background and border.

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +
Why are we haing two display-none?

2023-10-24 05:49 UTC, teckcipher commented on css/index.css
> +  }
Can we use `d-none-md` here instead? This way we are able to define display none for all medium screens. We can do similar for very large screens by defining `d-none-xl` or `d-none-lg`.

2023-10-25 18:28 UTC, merged